FROM ubuntu:18.04

# install settings
ARG INSTALL_DIR=/opt
ARG POSTGRES_OPTTUNE_DIR=${INSTALL_DIR}/postgres_opttune
ARG OLTP_DIR=${INSTALL_DIR}/oltpbench
ARG POSTGRES_HOME_DIR=/var/lib/postgresql
ARG PGDATA=${POSTGRES_HOME_DIR}/12/main
ARG PGENV=/etc/postgresql/12/main
ENV DEBIAN_FRONTEND=noninteractive

# git settings
ARG git_user
ARG git_pass
ENV git_user=${git_user}
ENV git_pass=${git_pass}
ARG GIT_OPTTUNE=https://github.com/ssl-oyamata/postgres_opttune
ARG GIT_OLTPBENCH=https://github.com/oltpbenchmark/oltpbench

# apt-get install dependencies
RUN apt-get update \
    &&  apt-get install -y \
        git \
        vim \
        bash-completion \
        lsb-release \
        wget \
        sudo \
        gcc

# python3 install
RUN apt install -y \
        python3.6 \
        python3-pip \
        python3-dev \
        python3-tk

# ant install
RUN wget http://ftp.riken.jp/net/apache//ant/binaries/apache-ant-1.10.7-bin.tar.gz -P /tmp
RUN tar zxf /tmp/apache-ant-1.10.7-bin.tar.gz -C /tmp
RUN mv /tmp/apache-ant-1.10.7 /usr/share/ant
RUN ln -s /usr/share/ant/bin/ant /usr/bin/ant
ENV ANT_HOME=/usr/share/ant

# java install
WORKDIR ${INSTALL_DIR}
RUN apt install -y openjdk-8-jdk
RUN echo "\n\
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre \n\
export PATH=$PATH:$JAVA_HOME/bin \n\
export CLASSPATH=.:$JAVA_HOME/lib \n\
" >> /root/.bashrc

# PostgreSQL install
RUN wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
RUN set -x \
    &&  apt-get update \
    &&  apt -y upgrade --no-install-recommends \
    &&  apt-get install -y \
        postgresql-12 \
        postgresql-client-12 \
        libpq-dev 
        
# postgresql setting file edit
USER postgres
WORKDIR ${POSTGRES_HOME_DIR}
RUN rm -rf ${PGDATA}
RUN cp -p ${PGENV}/postgresql.conf ${PGENV}/postgresql.conf.org
COPY ./config/postgresql_ubuntu.conf ${PGENV}/postgresql.conf
RUN cp -p ${PGENV}/pg_hba.conf ${PGENV}/pg_hba.conf.org
RUN sed -e s/"local   all             postgres                                peer"/"local   all             postgres                                trust"/g ${PGENV}/pg_hba.conf > ${PGENV}/pg_hba.conf.chenge
RUN mv ${PGENV}/pg_hba.conf.chenge ${PGENV}/pg_hba.conf
RUN cp -p ${PGENV}/pg_ctl.conf ${PGENV}/pg_ctl.conf.org
RUN sed -e s/"pg_ctl_options = ''"/"pg_ctl_options = '-t 300'"/g ${PGENV}/pg_ctl.conf > ${PGENV}/pg_ctl.conf.change
RUN mv ${PGENV}/pg_ctl.conf.change ${PGENV}/pg_ctl.conf

# postgresql Database create
USER postgres
WORKDIR ${POSTGRES_HOME_DIR}
RUN set -x \
    && /usr/lib/postgresql/12/bin/pg_ctl initdb -o "--encoding=UTF8 --locale=C" -D ${PGDATA} \
    && /usr/lib/postgresql/12/bin/pg_ctl -D ${PGDATA} start \
    && /usr/lib/postgresql/12/bin/createdb tpcc \
    && /usr/lib/postgresql/12/bin/createdb study_history

# Change default locale to ja-JP.UTF-8
USER root
ENV LANG=ja_JP.UTF-8
RUN localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

# install oltpbench
USER root
RUN echo "\n\
machine github.com \n\
login ${git_user} \n\
password ${git_pass} \n\
" > ~/.netrc
WORKDIR ${INSTALL_DIR}
RUN git clone ${GIT_OLTPBENCH} oltpbench
WORKDIR ${OLTP_DIR}
RUN ["/bin/bash", "-c", "source /root/.bashrc"] \
    && /usr/bin/ant bootstrap \
    && /usr/bin/ant resolve \
    && /usr/bin/ant build

# postgres_opttune install
USER root
WORKDIR ${INSTALL_DIR}
ENV PATH=${PATH}:/usr/lib/postgresql/12/bin/
RUN git clone ${GIT_OPTTUNE} postgres_opttune
RUN pip3 install -r ${POSTGRES_OPTTUNE_DIR}/requirements.txt

# ssh install
RUN apt install -y openssh-server util-linux sysvinit-utils
RUN rm /etc/ssh/ssh_host_*key*
RUN dpkg-reconfigure openssh-server

# sqlite install
RUN apt install -y sqlite

# service start
WORKDIR ${INSTALL_DIR}
ENTRYPOINT service postgresql start && service ssh start && /bin/bash --login
